services:
  db:
    image: postgres:13
    container_name: db
    restart: always #container reinicia se morrer
    ports:
      - 2345:5432
    env_file:
      - .env #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
      - pg:/var/lib/postgresql/data

  ts_node_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/home/node/app/src
    container_name: ts_node_app
    expose:
      - '5000'
    ports:
      - 5000:5000
    depends_on:
      - db # sรณ sobe quando o postgres tiver no ar
    env_file:
      - .env #configurar DATABASE_URL
    command: npm start
volumes:
  pg: