name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        working-directory: ./back-end
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "147MgJ"
          envkey_POSTGRES_DB: "drivenops"
          envkey_DATABASE_URL: "postgres://postgres:147MgJ@db:5432/drivenops"
          file_name: .env.test
      - name: Run tests
        working-directory: ./back-end
        run: docker-compose -f docker-compose-test.yml run node_app npm run test
      - name: Build
        working-directory: ./back-end
        run: npm i && npm run build